### ISSUE TITLE
try to make message not refreshing

### ISSUE THREAD

**Issue by royal27** [MrEliasen/Zolid-AJAX-Chat#1]
after i send the message the page is refreshed and appear only the new message,i want to see all the message...how i fix this problem?

**Comment by a2u** [comment]
comment out line #65 from /js/chat.js

**Comment by MrEliasen** [comment]
Hey, I did not realise an issue was opened for this repo.
It is very old and very out of date. I would not suggest using it in production. It is no more than a learning/reference repo.

Thanks for the reply thought DantaDaro :+1:
